FROM docker.io/debian:trixie-slim

WORKDIR /app

RUN apt-get update && apt-get install sqlite3 -y && apt-get clean && rm -rf /var/lib/apt/lists/*

ADD https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64 ./dbmate
RUN chmod +x ./dbmate

COPY ./db/migrations ./migrations

ENV DBMATE_MIGRATIONS_DIR="./migrations"
ENV DBMATE_SCHEMA_FILE=""
ENV DATABASE_URL=""

# Default entrypoint and argument
ENTRYPOINT [ "./dbmate" ]
CMD [ "help" ]